- name: Configuring newly created EC2 instances
  hosts: all
  remote_user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 300

    - name: "install python for Ansible."
      become: true
      raw: test -e /user/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false
  roles:
    # - role: weareinteractive.environment
    #   become: true
    - role: setup
      become: true
    - role: configure_node_exporter
      become: true


  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml
