
- name: "Creates backend app directory"
  file:
    path: /home/ubuntu/backend_app
    state: directory

- name: "Unzip backend files to correct directory"
  unarchive: 
    src: artifact.tar.gz
    dest: /home/ubuntu/backend_app

- name: "Install dependencies for project"
  shell: |
    cd /home/ubuntu/backend_app
    npm i

- name: "Executing node"
  command:  pm2 start main.js
  args:
    chdir: /home/ubuntu/backend_app/dist
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup  systemd -u ubuntu --hp /home/ubuntu