
- name: "Creates backend app directory"
  file:
    path: ~/backend_app
    state: directory

- name: "Unzip backend files to correct directory"
  unarchive: 
    src: artifact.tar.gz
    dest: ~/backend_app

- name: "Install dependencies for project"
  shell: |
    cd ~/backend_app
    npm i

- name:  start app
  command:  pm2 start main.js
  args:
    chdir: ~/backend_app/dist
  environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup  systemd -u ubuntu --hp /home/ubuntu