- name: "remove dependencies that are no longer required"
  apt:
    autoremove: yes

- name: "add node from nodesource"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash

- name: "Install Node.JS 13"
  become: true
  apt:
    name: ["node.js"]
    state: latest
    update_cache: yes

- name: "Install zip utility."
  apt:
    name: [ "zip", "unzip" ]
    state: latest
    update_cache: yes

- name: "install pm2 globaly"
  npm:
    name: pm2
    global: yes



